services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend1:
    build: ./backend
    container_name: backend1
    environment:
      - SERVER_ID=backend1
    volumes:
      - ./backend/db.sqlite3:/api/db.sqlite3
    depends_on:
      - redis

  backend2:
    build: ./backend
    container_name: backend2
    environment:
      - SERVER_ID=backend2
    volumes:
      - ./backend/db.sqlite3:/api/db.sqlite3
    depends_on:
      - redis

  backend3:
    build: ./backend
    container_name: backend3
    environment:
      - SERVER_ID=backend3
    volumes:
      - ./backend/db.sqlite3:/api/db.sqlite3
    depends_on:
      - redis

  backend4:
    build: ./backend
    container_name: backend4
    environment:
      - SERVER_ID=backend4
    volumes:
      - ./backend/db.sqlite3:/api/db.sqlite3
    depends_on:
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
  controller:
    build: ./controller
    container_name: controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/strategies:/nginx_conf/strategies
      - ./nginx/active_upstream.conf:/nginx_conf/active_upstream.conf
    ports:
      - "5001:5000"
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
